fail_fast: false

default_language_version:
    python: python3.9

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v4.3.0"
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-ast
          - id: fix-byte-order-marker
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: destroyed-symlinks
          - id: mixed-line-ending
          - id: check-json
          - id: check-yaml

    - repo: https://github.com/pycqa/flake8
      rev: "4.0.1"
      hooks:
          - id: flake8

    - repo: https://github.com/asottile/add-trailing-comma
      rev: "v2.2.3"
      hooks:
          - id: add-trailing-comma
