[tool.poetry]
name = "burplist-frontend"
version = "0.0.0"
description = "A frontend repository for the Burplist project."
authors = ["Jerry Ng <ngshiheng@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pywebio = "1.5.2"
SQLAlchemy = "==1.4.31"
psycopg2-binary = "2.9.3"
cachetools = "==5.0.0"
environs = "==9.5.0"
pyecharts = "1.9.1"
pytz = "^2021.1"
sentry-sdk = "==1.5.4"

[tool.poetry.dev-dependencies]
autopep8 = "==1.6.0"
flake8 = "==4.0.1"
pylint = "2.12.2"
pre-commit = "==2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
