[tool.poetry]
name = "burplist-frontend"
version = "1.0.0"
description = "A frontend repository for the Burplist project."
authors = ["Jerry Ng <ngshiheng@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.6"
pywebio = "^1.3.3"
SQLAlchemy = "^1.4.22"
psycopg2-binary = "^2.9.1"
cachetools = "^4.2.2"
environs = "^9.3.2"
pyecharts = "^1.9.0"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
flake8 = "^3.9.2"
pylint = "^2.9.6"
pre-commit = "^2.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
