# TODO: Refactor this to get information from existing database
POPULAR_BEER_STYLES = [
    # Sorted by COUNT DESC
    'IPA',
    'Pale Ale',
    'Lager',
    'Stout',
    'Belgian Ale',
    'Golden Ale',
    'Sour Ale',
    'Gose',
    'Session IPA',
    'Hazy Ale',
    'Wheat Ale',
    'Imperial IPA',
    'Pilsner',
    'Ale',
    'Fruit Beer',
    'Porter',
    'Mead',
    'Tripel',
    'New England IPA',
    'Amber Ale',
    'Wheat',
    'Hazy IPA',
    'Quadrupel',
    'Double IPA',
    'NEIPA',
    'India Pale Ale',
    'Dark Ale',
    'Imperial Stout',
    'Session Ale',
]


POPULAR_BEER_BRANDS = [
    # Sorted by COUNT DESC
    'Lost Coast',
    'Garage Project',
    'Holgate',
    'Kona',
    'Hawkers',
    'Eagle Bay',
    'Nail',
    'Brewlander',
    'Deschutes',
    'Colonial',
    'Avery',
    'Sierra Nevada',
    'Little Creatures',
    'Great Divide',
    'Kaiju',
    'Green Flash',
    'Coronado',
    'Chouffe',
    'Collective Arts Brewing',
    'Deschutes Brewery',
    'Trouble Brewing',
    'Mikkeller',
    'New Belgium',
    'Behemoth Brewing Company',
    'Founders',
    'Stone',
    'Heart of Darkness',
    'Lagunitas',
    'Lindemans',
    'Golden Road',
    'Stone Brewing',
    'Rodenbach',
    'Rocky Ridge',
    'Alpine',
    'The Bruery',
    'Rocky Ridge Brewing Co.',
    'Blasta Brewing',
    'Thirsty',
    '4 Pines',
    'Heretic',
    'Schneider Weisse',
    'Deeds Brewing',
    'Rogue',
    'Pirate Life',
    'BrewDog',
    'Gorilla Brewing',
    'Epic',
    'Blasta Brewing Co.',
    'Duvel',
    'Anderson Valley Brewing Co.',
    'Brothers',
    'Playground Brewery',
    'Brewdog',
    'Wayward',
    'St. Bernardus',
    'Off Day Beer Company',
    'Otherside Brewing Company',
    'Vedett',
    'Lion City Meadery',
    'Stone Brewing Co.',
    'Mother Earth',
    'Founders Brewing Co',
    'Stockade',
    'Thornbridge',
    'Mike Hess',
    'Anderson Valley Brewing',
    'Vocation Brewery',
    'Brewlander & Co',
    'Heretic Brewing Company',
    'Pizza Port',
    'Heretic Brewing Co.',
    'Brewerkz',
    'Huyghe',
    'Rochefort',
    'Magic Rock Brewing',
    'Bosteels',
    'Deep Creek Brewing Company',
    'Young Master',
    'Wychwood',
    'Behemoth Brewing',
    'Feral Brewing Co',
    'Westmalle',
    'The 1925 Brewing Co.',
    'St Bernardus',
    'Maui',
    'The 1925 Brewing Company',
    'Salt Beer Factory',
    'Gage Roads',
    'Founders Brewing Co.',
    'Otherside Brewing Co.',
    'Pirate Life Brewing',
    'Atomic',
    'Founders Brewing',
    'Lion Brewery',
    'Chillhops Brewing Co.',
    'Ska',
    'Van Honsebrouck',
    'Van Steenberge',
    'Erdinger',
    'La Trappe',
    'Adroit Theory Brewing',
    'Delirium',
    'Sierra Nevada Brewing Co.',
    'Gorilla',
    'Levante',
    'Gosnells',
    'Devil\'s Peak',
    'Pabst Blue Ribbon',
    'Sweetwater Brewery',
    'Leffe',
    'Thatchers Cider',
    'ParrotDog',
    'Chimay',
    'Paulaner',
    'Archipelago',
    '3 Fonteinen',
    'Co-conspirators Brewing Co',
    'Deep Creek',
    'Affligem',
    'Dogfish Head',
    'La Trappe',
    'Duncan\'s Brewing Company',
    'Brouwerij St. Bernardus',
    'Epic Brewing Company',
    'Barossa Valley Brewing',
    'Otherside Brewing',
    'Hoegaarden',
    'Brouwerij 3 Fonteinen',
    'Epic Brewing',
    'Rochefort Brewery',
    'Two Tribes',
    'Omnipollo',
    'Rye & Pint',
    'Anderson Valley',
    'North Coast Brewing',
    'Hitachino Nest',
    'North Coast Brewing Co.',
    'Drake\'s',
    'Rogue Ales',
    'Gweilo',
    'Veltins',
    'Liberty Brewing',
    'Boon Oude Geuze',
    'Moon Dog Brewery',
    'Orval',
    'Pabst',
    'Brooklyn',
    'Brouwerij Verhaeghe',
    'Young Master Brewery',
    'Fourpure Brewing Co',
    'Stockade Brew Co',
    'Dupont',
    'Estrella',
    'Samuel Adams',
    'Gosnells Mead',
    'Coedo',
    'Gosnells of London',
]

POPULAR_BEERS = [
    'Kona Big Wave Hawaiian Golden Ale',
    'Green Flash Saturhaze Session Hazy IPA',
    'Kona Longboard Hawaiian Lager',
    'Lost Coast Peanut Butter Chocolate Milk Stout',
    'Green Flash Tropical DNA Hazy IPA',
    'New Belgium Voodoo Ranger Juicy Haze IPA',
    'Lost Coast Hazy IPA',
    'Duvel Tripel Hop Belgian IPA',
    'Rodenbach Classic Belgian Sour Flemish Ale',
    'Rogue Batsquatch Hazy IPA',
    'Eagle Bay Australian India Pale Lager',
    'Chouffe Blanche Belgian Wheat Ale',
    'Coronado Pineapple Farm Hazy IPA',
    'Hawkers Australian Hazy Pale Ale',
    'Colonial Australian Southwest Sour Ale',
    'Brewlander Euphoria Double Dry Hopped Hazy IPA',
    'Sierra Nevada Hazy Little Thing IPA',
    'Levante x Team Secret A.F.K. Gamer\'s Hazy IPA',
    'Little Creatures Dog Days Australian Session IPA',
    'Stone Tangerine Express Hazy IPA',
    'Golden Road Hazy Los Angeles IPA',
    'Great Divide Hercules God style Double IPA',
    'Kaiju Aftermath Ultra Hopped Double IPA',
    'Mike Hess Hop Cloud Hazy IPA',
    'New Belgium Voodoo Ranger IPA',
    'Kona Hanalei Hawaiian Session IPA with Passion Fruit Orange Guava',
    'New Belgium Fat Tire Amber Ale',
    'Nail Super VPA Imperial IPA with Lemon Lime Rind',
    'Mike Hess Habitus Double IPA',
    'Dogfish Head 90 Minute Imperial IPA',
    'Coronado Never Better Double IPA',
    'Sierra Nevada Fantastic Haze Hazy Imperial IPA',
    'Deschutes Fresh Haze Citrus Hazy IPA',
    'Eagle Bay Australian Pale Ale',
    'Lost Coast Revenant IPA',
    'Colonial Australian Pale Ale',
    'Founders All Day Session IPA',
    'Pizza Port Ponto Session IPA',
    'Lost Coast Sharkinator Session Wheat IPA',
    'Lost Coast Tangerine Wheat Ale',
    'Eagle Bay Australian Lager',
    'Great Divide Car Camper Hazy Pale Ale',
    'Avery Hazyish Hazy IPA',
    'Colonial Australian IPA',
    'Brewlander Courage Double IPA',
    'Lagunitas Daytime Lo Cal Low Carb Session IPA',
    'Stone FML Fear. Movie. Lions. Hazy Double IPA',
    'Rodenbach Grand Cru Oak Aged Belgian Sour Flemish Ale',
    'Great Divide Fastpack Lo Cal Low Carb Hazy IPA',
    'Lagunitas Hazy Wonder Hazy IPA',
    'Green Flash Soul Style IPA',
    'Vedett Extra Pilsner Belgian Lager',
    'Vedett Extra Ordinary Belgian IPA',
    'Founders Centennial IPA',
    'Wychwood Hobgoblin Gold English Golden Ale',
    'Wychwood Hobgoblin Ruby English Amber Ale',
]


RESULTS_NOT_FOUND_GIFS = [
    'https://media.giphy.com/media/VHrSW9jIYrlat3PwIB/giphy.gif',  # Morty
    'https://media.giphy.com/media/1USKMDPjuH4ovL7J5h/giphy.gif',  # Rick
    'https://media.giphy.com/media/TGKwNUQ11E9LnACDLe/giphy.gif',  # Morty
    'https://media.giphy.com/media/WTiHD79xbtd53CgHpB/giphy.gif',  # Mr. Meeseeks
    'https://media.giphy.com/media/QvH2Em7M2kb04VEOG2/giphy.gif',  # Jerry
    'https://media.giphy.com/media/M9gBSOsxQW3od0GwfW/giphy.gif',  # Summer
]

AMPLITUDE_TRACKING_SCRIPTS = r"""
$('head').append('<script type="text/javascript">(function(e,t){var n=e.amplitude||{_q:[],_iq:{}};var r=t.createElement("script") ;r.type="text/javascript" ;r.integrity="sha384-u0hlTAJ1tNefeBKwiBNwB4CkHZ1ck4ajx/pKmwWtc+IufKJiCQZ+WjJIi+7C6Ntm" ;r.crossOrigin="anonymous";r.async=true ;r.src="https://cdn.amplitude.com/libs/amplitude-8.1.0-min.gz.js" ;r.onload=function(){if(!e.amplitude.runQueuedFunctions){console.log("[Amplitude] Error: could not load SDK")}};var i=t.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i) ;function s(e,t){e.prototype[t]=function(){this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));return this}}var o=function(){this._q=[];return this};var a=["add","append","clearAll","prepend","set","setOnce","unset","preInsert","postInsert","remove"] ;for(var c=0;c<a.length;c++){s(o,a[c])}n.Identify=o;var u=function(){this._q=[] ;return this};var l=["setProductId","setQuantity","setPrice","setRevenueType","setEventProperties"] ;for(var p=0;p<l.length;p++){s(u,l[p])}n.Revenue=u ;var d=["init","logEvent","logRevenue","setUserId","setUserProperties","setOptOut","setVersionName","setDomain","setDeviceId","enableTracking","setGlobalUserProperties","identify","clearUserProperties","setGroup","logRevenueV2","regenerateDeviceId","groupIdentify","onInit","logEventWithTimestamp","logEventWithGroups","setSessionId","resetSessionId"] ;function v(e){function t(t){e[t]=function(){e._q.push([t].concat(Array.prototype.slice.call(arguments,0)))}}for(var n=0;n<d.length;n++){t(d[n])}}v(n);n.getInstance=function(e){e=(!e||e.length===0?"$default_instance":e).toLowerCase() ;if(!Object.prototype.hasOwnProperty.call(n._iq,e)){n._iq[e]={_q:[]};v(n._iq[e])}return n._iq[e]};e.amplitude=n})(window,document); amplitude.getInstance().init("b5c55c2974a58b1c85cdd80332431d44");</script>')
"""
