# TODO: Refactor this to get information from existing database
POPULAR_BEER_STYLES = [
    # Sorted by COUNT DESC
    'IPA',
    'Pale Ale',
    'Lager',
    'Stout',
    'Belgian Ale',
    'Golden Ale',
    'Sour Ale',
    'Gose',
    'Session IPA',
    'Hazy Ale',
    'Wheat Ale',
    'Imperial IPA',
    'Pilsner',
    'Ale',
    'Fruit Beer',
    'Porter',
    'Mead',
    'Tripel',
    'New England IPA',
    'Amber Ale',
    'Wheat',
    'Hazy IPA',
    'Quadrupel',
    'Double IPA',
    'NEIPA',
    'India Pale Ale',
    'Dark Ale',
    'Imperial Stout',
    'Session Ale',
]


POPULAR_BEER_BRANDS = [
    # Sorted by COUNT DESC
    'Lost Coast',
    'Garage Project',
    'Holgate',
    'Kona',
    'Hawkers',
    'Eagle Bay',
    'Nail',
    'Brewlander',
    'Deschutes',
    'Colonial',
    'Avery',
    'Sierra Nevada',
    'Little Creatures',
    'Great Divide',
    'Kaiju',
    'Green Flash',
    'Coronado',
    'Chouffe',
    'Collective Arts Brewing',
    'Deschutes Brewery',
    'Trouble Brewing',
    'Mikkeller',
    'New Belgium',
    'Founders',
    'Stone',
    'Heart of Darkness',
    'Lagunitas',
    'Lindemans',
    'Golden Road',
    'Rodenbach',
    'Rocky Ridge',
    'Alpine',
    'The Bruery',
    'Blasta Brewing',
    'Thirsty',
    '4 Pines',
    'Heretic',
    'Schneider Weisse',
    'Deeds Brewing',
    'Rogue',
    'Pirate Life',
    'BrewDog',
    'Duvel',
    'Anderson Valley',
    'Brothers',
    'Playground Brewery',
    'Wayward',
    'Off Day Beer Company',
    'Otherside',
    'Vedett',
    'Lion City Meadery',
    'Mother Earth',
    'Stockade',
    'Thornbridge',
    'Mike Hess',
    'Vocation Brewery',
    'Pizza Port',
    'Brewerkz',
    'Huyghe',
    'Rochefort',
    'Magic Rock Brewing',
    'Bosteels',
    'Young Master',
    'Wychwood',
    'Behemoth Brewing',
    'Feral Brewing Co',
    'Westmalle',
    '1925',
    'St Bernardus',
    'Maui',
    'Salt Beer Factory',
    'Gage Roads',
    'Atomic',
    'Lion Brewery',
    'Chillhops Brewing Co.',
    'Ska',
    'Van Honsebrouck',
    'Van Steenberge',
    'Erdinger',
    'La Trappe',
    'Adroit Theory Brewing',
    'Delirium',
    'Gorilla',
    'Levante',
    'Gosnells',
    'Devil\'s Peak',
    'Sweetwater Brewery',
    'Leffe',
    'Thatchers Cider',
    'ParrotDog',
    'Chimay',
    'Paulaner',
    'Archipelago',
    '3 Fonteinen',
    'Co-conspirators Brewing Co',
    'Deep Creek',
    'Affligem',
    'Dogfish Head',
    'Duncan\'s Brewing Company',
    'Brouwerij',
    'Barossa Valley Brewing',
    'Hoegaarden',
    'Epic Brewing',
    'Two Tribes',
    'Omnipollo',
    'Rye & Pint',
    'North Coast Brewing',
    'Hitachino Nest',
    'Drake\'s',
    'Rogue Ales',
    'Gweilo',
    'Veltins',
    'Liberty Brewing',
    'Boon Oude Geuze',
    'Moon Dog Brewery',
    'Orval',
    'Pabst',
    'Brooklyn',
    'Fourpure Brewing Co',
    'Dupont',
    'Estrella',
    'Samuel Adams',
    'Coedo',
]

POPULAR_BEERS = [
    'Kona Big Wave Hawaiian Golden Ale',
    'Green Flash Saturhaze Session Hazy IPA',
    'Kona Longboard Hawaiian Lager',
    'Lost Coast Peanut Butter Chocolate Milk Stout',
    'Green Flash Tropical DNA Hazy IPA',
    'New Belgium Voodoo Ranger Juicy Haze IPA',
    'Lost Coast Hazy IPA',
    'Duvel Tripel Hop Belgian IPA',
    'Rodenbach Classic Belgian Sour Flemish Ale',
    'Rogue Batsquatch Hazy IPA',
    'Eagle Bay Australian India Pale Lager',
    'Chouffe Blanche Belgian Wheat Ale',
    'Coronado Pineapple Farm Hazy IPA',
    'Hawkers Australian Hazy Pale Ale',
    'Colonial Australian Southwest Sour Ale',
    'Brewlander Euphoria Double Dry Hopped Hazy IPA',
    'Sierra Nevada Hazy Little Thing IPA',
    'Levante x Team Secret A.F.K. Gamer\'s Hazy IPA',
    'Little Creatures Dog Days Australian Session IPA',
    'Stone Tangerine Express Hazy IPA',
    'Golden Road Hazy Los Angeles IPA',
    'Great Divide Hercules God style Double IPA',
    'Kaiju Aftermath Ultra Hopped Double IPA',
    'Mike Hess Hop Cloud Hazy IPA',
    'New Belgium Voodoo Ranger IPA',
    'Kona Hanalei Hawaiian Session IPA with Passion Fruit Orange Guava',
    'New Belgium Fat Tire Amber Ale',
    'Nail Super VPA Imperial IPA with Lemon Lime Rind',
    'Mike Hess Habitus Double IPA',
    'Dogfish Head 90 Minute Imperial IPA',
    'Coronado Never Better Double IPA',
    'Sierra Nevada Fantastic Haze Hazy Imperial IPA',
    'Deschutes Fresh Haze Citrus Hazy IPA',
    'Eagle Bay Australian Pale Ale',
    'Lost Coast Revenant IPA',
    'Colonial Australian Pale Ale',
    'Founders All Day Session IPA',
    'Pizza Port Ponto Session IPA',
    'Lost Coast Sharkinator Session Wheat IPA',
    'Lost Coast Tangerine Wheat Ale',
    'Eagle Bay Australian Lager',
    'Great Divide Car Camper Hazy Pale Ale',
    'Avery Hazyish Hazy IPA',
    'Colonial Australian IPA',
    'Brewlander Courage Double IPA',
    'Lagunitas Daytime Lo Cal Low Carb Session IPA',
    'Stone FML Fear. Movie. Lions. Hazy Double IPA',
    'Rodenbach Grand Cru Oak Aged Belgian Sour Flemish Ale',
    'Great Divide Fastpack Lo Cal Low Carb Hazy IPA',
    'Lagunitas Hazy Wonder Hazy IPA',
    'Green Flash Soul Style IPA',
    'Vedett Extra Pilsner Belgian Lager',
    'Vedett Extra Ordinary Belgian IPA',
    'Founders Centennial IPA',
    'Wychwood Hobgoblin Gold English Golden Ale',
    'Wychwood Hobgoblin Ruby English Amber Ale',
]


RESULTS_NOT_FOUND_GIFS = [
    'https://media.giphy.com/media/VHrSW9jIYrlat3PwIB/giphy.gif',  # Morty
    'https://media.giphy.com/media/1USKMDPjuH4ovL7J5h/giphy.gif',  # Rick
    'https://media.giphy.com/media/TGKwNUQ11E9LnACDLe/giphy.gif',  # Morty
    'https://media.giphy.com/media/WTiHD79xbtd53CgHpB/giphy.gif',  # Mr. Meeseeks
    'https://media.giphy.com/media/QvH2Em7M2kb04VEOG2/giphy.gif',  # Jerry
    'https://media.giphy.com/media/M9gBSOsxQW3od0GwfW/giphy.gif',  # Summer
]


GA_JS_FILE = "https://www.googletagmanager.com/gtag/js?id=G-TLTRLY136L"

GA_JS_CODE = """
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'G-YW0GRZJ8MT');
"""
