name: Release
on:
    push:
        branches:
            - main
        paths:
            - "**.py"
            - "poetry.lock"
jobs:
    test:
        uses: ./.github/workflows/test.yml
    semantic-release:
        runs-on: ubuntu-latest
        concurrency: release
        needs:
            - test
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Semantic Release
              uses: relekang/python-semantic-release@v7.28.1
              with:
                  github_token: "${{ secrets.GITHUB_TOKEN }}"
