name: Release
on:
    push:
        branches:
            - production
jobs:
    test:
        uses: ./.github/workflows/test.yml
    semantic-release:
        runs-on: ubuntu-latest
        concurrency: release
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Semantic Release
              uses: relekang/python-semantic-release@master
              with:
                  github_token: "${{ secrets.GITHUB_TOKEN }}"
